# Generated by Django 4.2.23 on 2025-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permissionuser',
            name='unique_permission_user',
        ),
        migrations.AddConstraint(
            model_name='permissionuser',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='unique_permission_user'),
        ),
    ]
