# Generated by Django 4.2.23 on 2025-07-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_permissionuser_unique_permission_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_department',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_division',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_limited',
        ),
    ]
