# Generated by Django 4.2.23 on 2025-07-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_role_is_department_remove_role_is_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pinfl',
        ),
    ]
